freebsd_instance:
  image: freebsd-12-1-release-amd64

task:
  install_script:
    - sudo tzsetup America/New_York
    - sudo pkg install -y p5-App-cpanminus git
    - sudo cpanm -n -q --installdeps .
  script:
    - perl Makefile.PL
    - make
    - make test
